### ISSUE TITLE
Uncertainty detached from graph?

### ISSUE THREAD

**Issue by Parskatt** [qianqianwang68/caps#3]
Hi,

Here:
https://github.com/qianqianwang68/caps/blob/8fcf29270d12c67d2f2bf326049e575420b171fe/CAPS/criterion.py#L19-L23

The uncertainty weight is detached from the computational graph.
Could you provide some intuition as to why this is done?

**Comment by qianqianwang68** [comment]
Hi, good question. We detached the weight because otherwise it may cause degenerate issues.  If we allow gradient from the weight, then instead of trying to minimize the epipolar distance, the network might just choose to reduce its weight in the loss, and that is not what we want. Hope this makes some sense.

**Comment by Parskatt** [comment]
Hi, thanks for the reply.

Having the gradients attached did degenerate the learning as you mention. Although I thought this would in theory be counteracted by the normalization which is done. Anyway, I'll close this issue.
